#pragma once

// Copie para secrets.h. O arquivo secrets.h é ignorado pelo Git.
#define IDMAQ "ADP-001"
#define WIFI_SSID "SUA_REDE_WIFI"
#define WIFI_PASSWORD "SUA_SENHA_WIFI"
#define DEVICE_API_KEY "CHAVE_UNICA_GERADA_NO_CADASTRO_DO_DISPOSITIVO"
#define MQTT_USER "USUARIO_MQTT_EXCLUSIVO_DO_DISPOSITIVO"
#define MQTT_PASSWORD "SENHA_MQTT_EXCLUSIVA_DO_DISPOSITIVO"

// Certificado raiz PEM usado tanto pelo HTTPS quanto pelo MQTT TLS.
static const char ROOT_CA_CERT[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
SUBSTITUA_PELO_CERTIFICADO_RAIZ_DOS_SERVIDORES
-----END CERTIFICATE-----
)EOF";
